"""Extract every real number the paper's result/data sections need.

Writes data/evaluation/paper_numbers.md - a reproducible single sheet feeding
the LaTeX author for V-A (Evaluation Design), V-C-1 (Dataset & Setup), and
V-C-3 (Cost & Latency). All numbers come from the committed matrix data via
`evaluation/matrix_stats.py`, so they match Table V and the figures.

Usage:
    python scripts/make_paper_numbers.py
"""
from __future__ import annotations

import statistics as stats
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from evaluation import matrix_stats as ms  # noqa: E402

OUT = ms.DATA_DIR / "paper_numbers.md"

# Anthropic-billed tiers only (qwen7b runs locally; its recorded cost is a
# pricing-table artifact, so we report its latency but not a dollar figure).
ANTHROPIC_TIERS = {"haiku", "sonnet"}


def _mean(xs):
    xs = [x for x in xs if x is not None]
    return stats.mean(xs) if xs else None


def cost_latency(cell: ms.Cell) -> dict:
    a_time = _mean([r["adapt_ai"].get("time") for r in cell.records])
    b_time = _mean([r["baseline"].get("time") for r in cell.records])
    a_cost = _mean([r["adapt_ai"].get("total_cost_usd") for r in cell.records])
    b_cost = _mean([r["baseline"].get("cost") for r in cell.records])
    a_in = _mean([r["adapt_ai"].get("total_input_tokens") for r in cell.records])
    a_out = _mean([r["adapt_ai"].get("total_output_tokens") for r in cell.records])
    b_in = _mean([r["baseline"].get("input_tokens") for r in cell.records])
    b_out = _mean([r["baseline"].get("output_tokens") for r in cell.records])

    # per-agent cost split (primary / quality; compliance is rule-based, no LLM)
    agent_cost: dict[str, list[float]] = defaultdict(list)
    for r in cell.records:
        usage = r["adapt_ai"].get("llm_usage") or {}
        per_q: dict[str, float] = defaultdict(float)
        for call in usage.get("calls", []):
            per_q[call.get("agent", "unknown")] += call.get("cost_usd", 0.0)
        for agent, c in per_q.items():
            agent_cost[agent].append(c)

    return {
        "a_time": a_time, "b_time": b_time,
        "slowdown": (a_time / b_time) if (a_time and b_time) else None,
        "a_cost": a_cost, "b_cost": b_cost,
        "cost_ratio": (a_cost / b_cost) if (a_cost and b_cost) else None,
        "a_in": a_in, "a_out": a_out, "b_in": b_in, "b_out": b_out,
        "agent_cost": {k: _mean(v) for k, v in agent_cost.items()},
        "rat_pct": 100.0 * sum(1 for r in cell.records if r["adapt_ai"].get("use_rat"))
        / cell.n,
    }


def category_counts(cell: ms.Cell) -> dict:
    return dict(Counter(r["category"] for r in cell.records))


def main() -> None:
    cells = ms.load_all_cells()
    if not cells:
        sys.exit("ERROR: no matrix results. Run scripts/run_matrix.py first.")

    # Dataset sizes are per-domain (identical across models); read from any tier.
    dataset = {}
    for d in ms.DOMAINS:
        for m in ms.MODELS:
            if (m, d) in cells:
                dataset[d] = (cells[(m, d)].n, category_counts(cells[(m, d)]))
                break
    total_q = sum(n for n, _ in dataset.values())

    cl = {key: cost_latency(cell) for key, cell in cells.items()}

    # Aggregate cost/latency over Anthropic tiers (the billable headline).
    def agg(metric):
        vals = [cl[k][metric] for k in cl if k[0] in ANTHROPIC_TIERS
                and cl[k][metric] is not None]
        return _mean(vals)

    L = []
    w = L.append
    w("# Paper numbers (auto-generated)\n")
    w("> Generated by `scripts/make_paper_numbers.py` from the committed matrix "
      "data in `data/evaluation/matrix/`. Every figure here matches Table V "
      "(`table5_cross_model.tex`) and the plots (`figures/`).\n")

    #  V-C-1
    w("## V-C-1 Dataset and Setup\n")
    w(f"- **Total evaluation queries per model:** {total_q} open-ended questions "
      f"({' + '.join(f'{d} {n}' for d, (n, _) in dataset.items())}).")
    w(f"- **Models (capability tiers):** Qwen2.5-7B-Instruct (local Ollama), "
      f"Claude Haiku 4.5, Claude Sonnet 4.6 — {len(cells)} of "
      f"{len(ms.MODELS) * len(ms.DOMAINS)} (model×domain) cells present.")
    w(f"- **Arms per query:** 2 (ADAPT-AI full pipeline vs. fair "
      f"`b1_disclaimer` single-call baseline) ⇒ "
      f"{total_q} × {len(cells)//len(ms.DOMAINS) if len(ms.DOMAINS) else 0} model "
      f"runs × 2 arms.")
    w("- **Per-domain question categories:**")
    for d, (n, cats) in dataset.items():
        cat_str = ", ".join(f"{k} {v}" for k, v in sorted(cats.items()))
        w(f"  - {ms.DOMAIN_LABELS[d]} (N={n}): {cat_str}")
    w("- **Safety-critical categories:** compliance_safety + hallucination_trap; "
      "**reasoning categories:** complex_reasoning + analysis + planning.")
    w("- **Judge:** Claude Opus (`claude-opus-4-8`), provider `anthropic`; "
      "guarded to refuse judge == system-under-test (corroboration only — "
      "reference-based metrics are the headline).")
    w("- **Baseline ladder:** `b0_bare → b1_disclaimer → b2_rag → b3_persona → "
      "full`; headline comparison is **full vs b1_disclaimer** (matched token "
      "budget, both disclaimer-instructed; safety scored disclaimer-independently).\n")

    #  V-A
    w("## V-A Evaluation Design\n")
    w("- **Metrics** (`evaluation/metrics.py`, `ResponseEvaluator`): BLEU-4, "
      "ROUGE-L, BERTScore, concept recall/F1 (negation-aware), safety score, "
      "critical omissions, hallucination-pattern matches.")
    w("- **Composite overall score** = 0.20·BLEU-4 + 0.10·ROUGE-L + "
      "0.40·concept-recall + 0.20·safety − 0.10·(critical omissions) − "
      "0.10·(hallucination matches).")
    w("- **Significance:** paired Wilcoxon signed-rank on overall score per cell; "
      "matched-pairs rank-biserial effect size; Holm–Bonferroni correction "
      f"across all {len(cells)} cells.")
    w("- **Headline result:** ADAPT-AI significantly beats the fair baseline in "
      "**legal on Haiku (Holm p=0.004)**; finance/Haiku is borderline "
      "(p=0.050); healthcare is a null across all tiers. The win concentrates "
      "in safety-critical questions (concept recall + false-premise refusal), "
      "**not** a toxicity reduction (raw safety score is at ceiling for both "
      "arms).")
    w("- **Human agreement:** κ subset + protocol in `evaluation/human_eval/`.\n")

    #  V-C-3
    w("## V-C-3 Cost and Latency\n")
    w("Per-question means. Cost is reported for the Anthropic-billed tiers only "
      "(Qwen runs locally; its latency is real, its dollar cost is a pricing-"
      "table artifact and is omitted).\n")
    w("| Model | Domain | ADAPT lat (s) | Base lat (s) | Slowdown | "
      "ADAPT $/q | Base $/q | Cost× | RAT% |")
    w("|-------|--------|--------------:|-------------:|---------:|"
      "----------:|---------:|-----:|-----:|")
    for m in ms.MODELS:
        for d in ms.DOMAINS:
            if (m, d) not in cl:
                continue
            c = cl[(m, d)]
            billed = m in ANTHROPIC_TIERS
            a_cost = f"${c['a_cost']:.5f}" if billed and c["a_cost"] else "—"
            b_cost = f"${c['b_cost']:.5f}" if billed and c["b_cost"] else "—"
            ratio = f"{c['cost_ratio']:.2f}×" if billed and c["cost_ratio"] else "—"
            w(f"| {ms.MODEL_LABELS[m]} | {ms.DOMAIN_LABELS[d]} "
              f"| {c['a_time']:.2f} | {c['b_time']:.2f} | {c['slowdown']:.2f}× "
              f"| {a_cost} | {b_cost} | {ratio} | {c['rat_pct']:.0f}% |")
    w("")
    w(f"- **Aggregate (Anthropic tiers):** ADAPT-AI is **{agg('cost_ratio'):.2f}× "
      f"more expensive** and **{agg('slowdown'):.2f}× slower** per question than "
      "the single-call baseline (multi-agent pipeline overhead).")

    # per-agent split aggregated over Anthropic tiers
    agent_acc: dict[str, list[float]] = defaultdict(list)
    for k in cl:
        if k[0] in ANTHROPIC_TIERS:
            for agent, c in cl[k]["agent_cost"].items():
                if c is not None:
                    agent_acc[agent].append(c)
    if agent_acc:
        w("- **Per-agent cost split (avg $/q, Anthropic tiers):** "
          + ", ".join(f"{a} ${_mean(v):.5f}" for a, v in sorted(agent_acc.items()))
          + " (compliance is rule-based — no LLM call).")
    w("")
    OUT.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))
    print(f"\n[Saved -> {OUT}]")


if __name__ == "__main__":
    main()
