"""Emit Table V (cross-model results) as LaTeX, from the shared stats source.

Reads `evaluation/matrix_stats.py` - the same module the figures use - so the
table and the plots are guaranteed to share one source of truth. Significance
is Holm-Bonferroni corrected across the 9 (model x domain) Wilcoxon tests;
significant cells (corrected p < 0.05) are bolded and flagged.

Outputs:
  data/evaluation/table5_cross_model.tex   - booktabs LaTeX table
  also prints a plain-text preview to stdout

Usage:
    python scripts/make_table5.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from evaluation import matrix_stats as ms  # noqa: E402

OUT = ms.DATA_DIR / "table5_cross_model.tex"


def _fmt_p(p: float) -> str:
    if p < 0.001:
        return "$<$0.001"
    return f"{p:.3f}"


def build_rows(cells: dict) -> tuple[list[dict], dict]:
    order = [(m, d) for m in ms.MODELS for d in ms.DOMAINS if (m, d) in cells]
    holm = ms.holm_over_cells(cells, order)
    rows = []
    for (m, d) in order:
        s = ms.summarise(cells[(m, d)])
        p_corr = holm[(m, d)]
        rows.append({
            "model": m,
            "domain": d,
            "n": s["n"],
            "adapt": s["adapt_mean"],
            "base": s["base_mean"],
            "delta": s["delta"],
            "r": s["r"],
            "p_corr": p_corr,
            "sig": p_corr < 0.05,
        })
    return rows, holm


def to_latex(rows: list[dict]) -> str:
    header = [
        r"% Auto-generated by scripts/make_table5.py - regenerate, do not hand-edit.",
        r"% Requires \usepackage{booktabs} and \usepackage{amsmath}.",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Cross-model results: ADAPT-AI (full pipeline) versus the fair",
        r"  \texttt{b1\_disclaimer} baseline on overall score. $\Delta$ is the mean",
        r"  paired difference; $r$ is the matched-pairs rank-biserial effect size;",
        r"  $p_{\text{corr}}$ is the Holm--Bonferroni-corrected Wilcoxon signed-rank",
        r"  value across all nine cells. \textbf{Bold} marks corrected $p<0.05$.}",
        r"  \label{tab:cross-model}",
        r"  \begin{tabular}{llrrrrrr}",
        r"    \toprule",
        r"    Model & Domain & $N$ & ADAPT & Base & $\Delta$ & $r$ & "
        r"$p_{\text{corr}}$ \\",
        r"    \midrule",
    ]
    body: list[str] = []
    prev_model = None
    for row in rows:
        if prev_model is not None and row["model"] != prev_model:
            body.append(r"    \midrule")
        model_disp = ms.MODEL_LABELS[row["model"]] if row["model"] != prev_model else ""
        prev_model = row["model"]

        adapt = f"{row['adapt']:.3f}"
        base = f"{row['base']:.3f}"
        delta = f"{row['delta']:+.3f}"
        rr = f"{row['r']:+.2f}"
        pc = _fmt_p(row["p_corr"])
        if row["sig"]:
            delta = rf"\textbf{{{delta}}}"
            pc = rf"\textbf{{{pc}}}"

        body.append(
            f"    {model_disp} & {ms.DOMAIN_LABELS[row['domain']]} & {row['n']} "
            f"& {adapt} & {base} & {delta} & {rr} & {pc} \\\\"
        )

    footer = [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
        "",
    ]
    return "\n".join(header + body + footer)


def preview(rows: list[dict]) -> str:
    out = [
        "Cross-Model Results (ADAPT-AI full vs b1_disclaimer baseline)",
        f"{'Model':<11}{'Domain':<12}{'N':>4}{'ADAPT':>8}{'Base':>8}"
        f"{'Δ':>8}{'r':>7}{'p_corr':>9}{'sig':>5}",
        "-" * 72,
    ]
    for row in rows:
        out.append(
            f"{ms.MODEL_LABELS[row['model']]:<11}{ms.DOMAIN_LABELS[row['domain']]:<12}"
            f"{row['n']:>4}{row['adapt']:>8.3f}{row['base']:>8.3f}"
            f"{row['delta']:>+8.3f}{row['r']:>+7.2f}{row['p_corr']:>9.3f}"
            f"{'  *' if row['sig'] else '':>5}"
        )
    return "\n".join(out)


def main() -> None:
    cells = ms.load_all_cells()
    if not cells:
        sys.exit("ERROR: no matrix results in data/evaluation/matrix/. "
                 "Run scripts/run_matrix.py first.")
    rows, _ = build_rows(cells)
    OUT.write_text(to_latex(rows), encoding="utf-8")
    print(preview(rows))
    print(f"\n[Saved LaTeX table -> {OUT}]")


if __name__ == "__main__":
    main()
